### ISSUE TITLE
Read operations into the tables are O(n) instead of O(1)

### ISSUE THREAD

**Issue by Victov** [gtker/wow_dbc#1]
Since the tables are regular Vecs, getting a row by its Key is a linear operation, it has to `find` the row. 
Storing the rows as `HashMap<KeyType, RowType>` would make lookups significantly faster. This requires key types to derive `Hash`.

This also enables library consumers to store rows and their types in HashMaps if they choose to do so for custom purposes.

**Comment by gtker** [comment]
I would like to have a more static guarantees from the type system, but the semantics of the DBC files prevent this from really being possible.

Namely:

* Not all tables have a primary key.
* Primary keys are not guaranteed to be unique.
* Foreign keys are not guaranteed to point to a valid row.
* Foreign keys are not guaranteed to point to a valid table.
* Some other wonkiness that I forgot.

I am definitely not against implementing `Hash` and all the other traits that I apparently forgot to implement though.

I also don't really think linearly scanning the array is that slow compared to a map considering the relatively limited amount of entries, but I would be open to benchmarks if anybody cares enough.

**Comment by Victov** [comment]
Thanks for implementing the traits. That should help!
